### PR TITLE
ApplicationScope request element is removed from FindCustomersOrCusto…

### PR DESCRIPTION
**Pull request by thechrisnixon**
…mersInfo in v12

### CODE REVIEW

**Comment by complex64** [comment]
@amirmanji, could I ask you to make a call if this should be merged or not?

**Comment by amirmanji** [comment]
Hello, I am here in the year 2020.

**Comment by amirmanji** [comment]
@dasnixon What's going on here? Should we just close this out or do we need to do it?

**Comment by thechrisnixon** [comment]
It doesn't look like `application_scope` is used as a query parameter anymore, even for v13 (current version we are on). This PR was initially for v12.

https://docs.microsoft.com/en-us/advertising/customer-management-service/findaccountsorcustomersinfo?view=bingads-13

**Comment by complex64** [comment]
> Hello, I am here in the year 2020.

I have bad news.

**Comment by thechrisnixon** [comment]
> > Hello, I am here in the year 2020.
> 
> I have bad news.

**Comment by thechrisnixon** [comment]
Going to close for now after discussing with @tenjin/front-end. It isn't causing problems from the bing side of things.

**Pull request closed without merging**
