### PR TITLE
Update to v13

### PR DESCRIPTION
**Pull request by vanner**
https://github.com/tenjin/issues/issues/182

### CODE REVIEW

**Review by thechrisnixon — COMMENTED** [review]
Did you test this?

**Comment by vanner** [comment]
Not yet. Will test on staging.

**Comment by complex64** [comment]
Anything we can help with on this? I list of steps and checks perhaps that we could walk through?

**Comment by makototaguchi1110** [comment]
doc says the depreciation date of our current version is Oct 31, 2019.

**Comment by vanner** [comment]
Testing tracker: https://github.com/tenjin/tracker/pull/4865

**Comment by vanner** [comment]
this was tested on staging and now in production with     

bing-ads-api (0.8.0)

**Pull request merged**
